-- Create table for Driver Leads (Pre-Signup)
create table if not exists public.driver_leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    full_name text not null,
    phone text not null,
    city text not null,
    doc_type text not null, -- 'ci', 'ruc', 'pas'
    doc_number text not null,
    vehicle_type text not null, -- 'car', 'moto'
    vehicle_brand text not null,
    vehicle_model text not null,
    availability text, -- 'full', 'part', 'casual'
    suggestions text,
    status text default 'pending' -- 'pending', 'contacted', 'approved', 'rejected'
);

-- Enable Row Level Security (RLS) is optional but recommended.
-- For now, we allow public insert if no auth is required for pre-signup, 
-- OR we can just keep it simple if the API keys are handled correctly.

-- Simple Policy: Allow anyone (anon) to insert leads.
alter table public.driver_leads enable row level security;

create policy "Enable insert for everyone"
on public.driver_leads for insert
with check (true);

-- Policy: Allow only admins/service_role to select/update (assuming dashboard usage)
-- For dev purposes, we might allow read too if needed, but 'insert' is critical for the form.
create policy "Enable select for authenticated users only"
on public.driver_leads for select
using (auth.role() = 'authenticated');
